# Generated by Django 5.0.4 on 2025-01-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0006_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolike',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
    ]
