version: '3.8'

services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  web:
    image: benkolov/workshop
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    environment:
      DJANGO_SETTINGS_MODULE: Workshop.settings
      DATABASE_URL: postgres://postgres-user:password@db:5432/workshop_db
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workshop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/staticfiles
      - mediafiles:/mediafiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
    driver: local
  staticfiles:
    driver: local
  mediafiles:
    driver: local
