# Generated by Django 5.0.4 on 2024-05-11 19:23

import Workshop.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='mediafiles/pet_photos/', validators=[Workshop.photos.validators.validate_image_less_than_5mb]),
        ),
    ]
