# Generated by Django 5.1.4 on 2025-02-07 10:07

import Workshop.photos.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[Workshop.photos.validators.validate_image_less_than_5mb]),
        ),
    ]
